swagger: '2.0'
info:
  description: >-
    Welcome to the swapi, the Star Wars API! This documentation should help you
    familiarise yourself with the resources available and how to consume them
    with HTTP requests. If you're after a native helper library then I suggest
    you scroll down and check out what's available. Read through the getting
    started section before you dive in. Most of your problems should be solved
    just by reading through it.
  version: ''
  title: Swapi
  contact:
    email: vmishra@grepruby.com
host: www.swapi.co
basePath: /api
tags:
  - name: films
    description: The URL root for Film resources
    externalDocs:
      description: Find out more
      url: 'http://swapi.co/api/films/'
  - name: people
    description: The URL root for People resources
    externalDocs:
      description: Find out more
      url: 'http://swapi.co/api/people/'
schemes:
  - http
paths:
  /films:
    get:
      tags:
        - Films
      summary: get all the film resources
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: title
          in: query
          description: title of the film to be returned.
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Films'
  '/films/{:id}':
    get:
      tags:
        - Films
      summary: get a specific film resource
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: ':id'
          in: path
          description: id of the film to be returned
          required: true
          type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Film'
  /films/schema:
    get:
      tags:
        - Films
      summary: view the JSON schema for this resource
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/FilmSchema'
  /people:
    get:
      tags:
        - People
      summary: get all the people resources
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: name
          in: query
          description: name of this person to be returned
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/People'
  '/people/{:id}':
    get:
      tags:
        - People
      summary: Get people by Id.
      description: get a specific people resource.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: ':id'
          in: path
          description: id of the people to be returned
          type: integer
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Person'
  /people/schema:
    get:
      tags:
        - People
      summary: view the JSON schema for this resource
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PeopleSchema'
definitions:
  Films:
    type: object
    properties:
      count:
        type: integer
        example: '7'
      next:
        type: string
        example: null
      previous:
        type: string
        example: null
      results:
        type: array
        items:
          type: object
          example:
            $ref: '#/definitions/Film'
  Film:
    type: object
    properties:
      title:
        type: string
        description: The title of the film
        example: A New Hope
      episode_id:
        type: integer
        description: The episode number of this film.
        example: 4
      opening_crawl:
        type: string
        description: The opening paragraphs at the beginning of this film.
        example: "It is a period of civil war.\n\nRebel spaceships, striking\n\nfrom a hidden base, have won\n\ntheir first victory against\n\nthe evil Galactic Empire.\n\n\n\nDuring the battle, Rebel\n\nspies managed to steal secret\r\nplans to the Empire's\n\nultimate weapon, the DEATH\n\nSTAR, an armored space\n\nstation with enough power\n\nto destroy an entire planet.\n\n\n\nPursued by the Empire's\n\nsinister agents, Princess\n\nLeia races home aboard her\n\nstarship, custodian of the\n\nstolen plans that can save her\n\npeople and restore\n\nfreedom to the galaxy...."
      director:
        type: string
        description: George Lucas
        example: A New Hope
      producer:
        type: string
        description: The name(s) of the producer(s) of this film. Comma separated.
        example: 'Gary Kurtz, Rick McCallum'
      release_date:
        type: string
        description: The ISO 8601 date format of film release at original creator country.
        example: '1977-05-25'
      characters:
        type: array
        items:
          type: string
        description: An array of people resource URLs that are in this film.
        example:
          - 'http://www.swapi.co/api/people/1/'
          - 'http://www.swapi.co/api/people/2/'
          - 'http://www.swapi.co/api/people/3/'
          - 'http://www.swapi.co/api/people/4/'
          - 'http://www.swapi.co/api/people/5/'
          - 'http://www.swapi.co/api/people/6/'
          - 'http://www.swapi.co/api/people/7/'
          - 'http://www.swapi.co/api/people/8/'
          - 'http://www.swapi.co/api/people/9/'
          - 'http://www.swapi.co/api/people/10/'
          - 'http://www.swapi.co/api/people/12/'
          - 'http://www.swapi.co/api/people/13/'
          - 'http://www.swapi.co/api/people/14/'
          - 'http://www.swapi.co/api/people/15/'
          - 'http://www.swapi.co/api/people/16/'
          - 'http://www.swapi.co/api/people/18/'
          - 'http://www.swapi.co/api/people/19/'
          - 'http://www.swapi.co/api/people/81/'
      planets:
        type: array
        items:
          type: string
        description: An array of planet resource URLs that are in this film.
        example:
          - 'http://www.swapi.co/api/planets/2/'
          - 'http://www.swapi.co/api/planets/3/'
          - 'http://www.swapi.co/api/planets/1/'
      starships:
        type: array
        items:
          type: string
        description: An array of starship resource URLs that are in this film.
        example:
          - 'http://www.swapi.co/api/starships/2/'
          - 'http://www.swapi.co/api/starships/3/'
          - 'http://www.swapi.co/api/starships/5/'
          - 'http://www.swapi.co/api/starships/9/'
          - 'http://www.swapi.co/api/starships/10/'
          - 'http://www.swapi.co/api/starships/11/'
          - 'http://www.swapi.co/api/starships/12/'
          - 'http://www.swapi.co/api/starships/13/'
      vehicles:
        type: array
        items:
          type: string
        description: An array of vehicle resource URLs that are in this film.
        example:
          - 'http://www.swapi.co/api/vehicles/4/'
          - 'http://www.swapi.co/api/vehicles/6/'
          - 'http://www.swapi.co/api/vehicles/7/'
          - 'http://www.swapi.co/api/vehicles/8/'
      species:
        type: array
        items:
          type: string
        description: An array of species resource URLs that are in this film.
        example:
          - 'http://www.swapi.co/api/species/5/'
          - 'http://www.swapi.co/api/species/3/'
          - 'http://www.swapi.co/api/species/2/'
          - 'http://www.swapi.co/api/species/1/'
          - 'http://www.swapi.co/api/species/4/'
      created:
        type: string
        description: the ISO 8601 date format of the time that this resource was created.
        example: '2014-12-10T14:23:31.880000Z'
      edited:
        type: string
        description: the ISO 8601 date format of the time that this resource was edited.
        example: '2014-12-12T11:24:39.858000Z'
      url:
        type: string
        description: the hypermedia URL of this resource.
        example: 'http://swapi.co/api/films/1/'
  FilmSchema:
    type: object
    properties:
      description:
        type: string
        example: A Star Wars film
      title:
        type: string
        example: Film
      type:
        type: string
        example: object
      required:
        type: array
        items:
          type: string
        example:
          - title
          - episode_id
          - opening_crawl
          - director
          - producer
          - release_date
          - characters
          - planets
          - starships
          - vehicles
          - species
          - url
          - created
          - edited
      $schema:
        type: string
        example: 'http://json-schema.org/draft-04/schema'
      properties:
        type: object
        properties:
          producer:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The producer(s) of this film.
          created:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: >-
                  The ISO 8601 date format of the time that this resource was
                  created.
              format:
                type: string
                example: date-time
          title:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The title of this film.
          director:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The director of this film.
          release_date:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The release date at original creator country.
              format:
                type: string
                example: date
          url:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The url of this resource.
              format:
                type: string
                example: uri
          edited:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: >-
                  the ISO 8601 date format of the time that this resource was
                  edited.
              format:
                type: string
                example: date-time
          species:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: The species resources featured within this film.
          characters:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: The people resources featured within this film.
          planets:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: The planet resources featured within this film.
          episode_id:
            type: object
            properties:
              type:
                type: string
                example: integer
              description:
                type: string
                example: The episode number of this film.
          starships:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: The starship resources featured within this film.
          opening_crawl:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The opening crawl text at the beginning of this film.
          vehicles:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: The vehicle resources featured within this film.
  People:
    type: object
    properties:
      count:
        type: integer
        example: '7'
      next:
        type: string
        example: null
      previous:
        type: string
        example: null
      results:
        type: array
        items:
          type: object
          example:
            $ref: '#/definitions/Person'
  Person:
    type: object
    properties:
      name:
        type: string
        description: The name of this person.
        example: Luke Skywalker
      birth_year:
        type: string
        description: >-
          The birth year of the person, using the in-universe standard of BBY or
          ABY - Before the Battle of Yavin or After the Battle of Yavin. The
          Battle of Yavin is a battle that occurs at the end of Star Wars
          episode IV: A New Hope.
        example: 19 BBY
      eye_color:
        type: string
        description: >-
          The eye color of this person. Will be "unknown" if not known or "n/a"
          if the person does not have an eye.
        example: Blue
      gender:
        type: string
        description: >-
          The gender of this person. Either "Male", "Female" or "unknown", "n/a"
          if the person does not have a gender.
        example: Male
      hair_color:
        type: string
        description: >-
          The hair color of this person. Will be "unknown" if not known or "n/a"
          if the person does not have hair.
        example: Blond
      height:
        type: string
        description: The height of the person in centimeters.
        example: '172'
      mass:
        type: string
        description: The mass of the person in kilograms.
        example: '77'
      skin_color:
        type: string
        description: The skin color of this person.
        example: Fair
      homeworld:
        type: string
        description: >-
          The URL of a planet resource, a planet that this person was born on or
          inhabits.
        example: 'http://swapi.co/api/planets/1/'
      films:
        type: array
        items:
          type: string
        description: An array of film resource URLs that this person has been in.
        example:
          - 'http://swapi.co/api/films/1/'
      species:
        type: array
        items:
          type: string
        description: An array of species resource URLs that this person belongs to.
        example:
          - 'http://swapi.co/api/species/1/'
      starships:
        type: array
        items:
          type: string
        description: An array of starship resource URLs that this person has piloted.
        example:
          - 'http://swapi.co/api/starships/12/'
      vehicles:
        type: array
        items:
          type: string
        description: An array of vehicle resource URLs that this person has piloted.
        example:
          - 'http://swapi.co/api/vehicles/14/'
      url:
        type: string
        description: the hypermedia URL of this resource.
        example: 'http://swapi.co/api/people/1/'
      created:
        type: string
        description: the ISO 8601 date format of the time that this resource was created.
        example: '2014-12-09T13:50:51.644000Z'
      edited:
        type: string
        description: the ISO 8601 date format of the time that this resource was edited.
        example: '2014-12-10T13:52:43.172000Z'
  PeopleSchema:
    type: object
    properties:
      description:
        type: string
        example: A person within the Star Wars universe.
      title:
        type: string
        example: People
      type:
        type: string
        example: object
      required:
        type: array
        example:
          - name
          - height
          - mass
          - hair_color
          - skin_color
          - eye_color
          - birth_year
          - gender
          - homeworld
          - films
          - species
          - vehicles
          - starships
          - url
          - created
          - edited
      $schema:
        type: string
        example: 'http://json-schema.org/draft-04/schema'
      properties:
        type: object
        properties:
          mass:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The mass of this person in kilograms.
          hair_color:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The hair color of this person.
          created:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: >-
                  The ISO 8601 date format of the time that this resource was
                  created.
              format:
                type: string
                example: date-time
          films:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: >-
                  An array of urls of film resources that this person has been
                  in.
          gender:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The gender of this person (if known).
          eye_color:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The eye color of this person.
          edited:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: >-
                  the ISO 8601 date format of the time that this resource was
                  edited.
              format:
                type: string
                example: date-time
          height:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The height of this person in meters.
          url:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The url of this resource.
              format:
                type: string
                example: uri
          homeworld:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The url of the planet resource that this person was born on.
          name:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The name of this person.
          vehicles:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: An array of vehicle resources that this person has piloted.
          starships:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: An array of starship resources that this person has piloted.
          birth_year:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: >-
                  The birth year of this person. BBY (Before the Battle of
                  Yavin) or ABY (After the Battle of Yavin).
          skin_color:
            type: object
            properties:
              type:
                type: string
                example: string
              description:
                type: string
                example: The skin color of this person.
          species:
            type: object
            properties:
              type:
                type: string
                example: array
              description:
                type: string
                example: The url of the species resource that this person is.
